export enum IconName {
	ARROW_SEND = 'ARROW_SEND',
	ARROW_BACK = 'ARROW_BACK',
	CLOSE = 'CLOSE',
	CHAT = 'CHAT',
	CLIP = 'CLIP',
	DOUBLE_CHECK = 'DOUBLE_CHECK',
	ONE_CHECK = 'ONE_CHECK',
	MAGNIFYING_GLASS = 'MAGNIFYING_GLASS',
	MORE_OPTIONS = 'MORE_OPTIONS',
	MICROPHONE = 'MICROPHONE',
	STATUS = 'STATUS',
	SMILEY = 'SMILEY',
}

export enum IconSizeTheme {
	DEFAULT = 'DEFAULT',
	SMALL = 'SMALL',
	LARGE = 'LARGE',
}
